/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as CommerciauxRouteImport } from './routes/commerciaux'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as TarificationRouteImport } from './routes/tarification'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as LivreursIndexRouteImport } from './routes/livreurs.index'
import { Route as LivreursIdRouteImport } from './routes/livreurs.$id'
import { Route as PartenairesIndexRouteImport } from './routes/partenaires.index'
import { Route as PartenairesIdRouteImport } from './routes/partenaires.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerciauxRoute = CommerciauxRouteImport.update({
  id: '/commerciaux',
  path: '/commerciaux',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const TarificationRoute = TarificationRouteImport.update({
  id: '/tarification',
  path: '/tarification',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreursIndexRoute = LivreursIndexRouteImport.update({
  id: '/livreurs/',
  path: '/livreurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreursIdRoute = LivreursIdRouteImport.update({
  id: '/livreurs/$id',
  path: '/livreurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesIndexRoute = PartenairesIndexRouteImport.update({
  id: '/partenaires/',
  path: '/partenaires/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesIdRoute = PartenairesIdRouteImport.update({
  id: '/partenaires/$id',
  path: '/partenaires/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/commerciaux': typeof CommerciauxRoute
  '/dispatch': typeof DispatchRoute
  '/paiements': typeof PaiementsRoute
  '/tarification': typeof TarificationRoute
  '/courses/$id': typeof CoursesIdRoute
  '/livreurs/$id': typeof LivreursIdRoute
  '/partenaires/$id': typeof PartenairesIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/livreurs/': typeof LivreursIndexRoute
  '/partenaires/': typeof PartenairesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/commerciaux': typeof CommerciauxRoute
  '/dispatch': typeof DispatchRoute
  '/paiements': typeof PaiementsRoute
  '/tarification': typeof TarificationRoute
  '/courses/$id': typeof CoursesIdRoute
  '/livreurs/$id': typeof LivreursIdRoute
  '/partenaires/$id': typeof PartenairesIdRoute
  '/courses': typeof CoursesIndexRoute
  '/livreurs': typeof LivreursIndexRoute
  '/partenaires': typeof PartenairesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/commerciaux': typeof CommerciauxRoute
  '/dispatch': typeof DispatchRoute
  '/paiements': typeof PaiementsRoute
  '/tarification': typeof TarificationRoute
  '/courses/$id': typeof CoursesIdRoute
  '/livreurs/$id': typeof LivreursIdRoute
  '/partenaires/$id': typeof PartenairesIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/livreurs/': typeof LivreursIndexRoute
  '/partenaires/': typeof PartenairesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agences'
    | '/commerciaux'
    | '/dispatch'
    | '/paiements'
    | '/tarification'
    | '/courses/$id'
    | '/livreurs/$id'
    | '/partenaires/$id'
    | '/courses/'
    | '/livreurs/'
    | '/partenaires/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agences'
    | '/commerciaux'
    | '/dispatch'
    | '/paiements'
    | '/tarification'
    | '/courses/$id'
    | '/livreurs/$id'
    | '/partenaires/$id'
    | '/courses'
    | '/livreurs'
    | '/partenaires'
  id:
    | '__root__'
    | '/'
    | '/agences'
    | '/commerciaux'
    | '/dispatch'
    | '/paiements'
    | '/tarification'
    | '/courses/$id'
    | '/livreurs/$id'
    | '/partenaires/$id'
    | '/courses/'
    | '/livreurs/'
    | '/partenaires/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencesRoute: typeof AgencesRoute
  CommerciauxRoute: typeof CommerciauxRoute
  DispatchRoute: typeof DispatchRoute
  PaiementsRoute: typeof PaiementsRoute
  TarificationRoute: typeof TarificationRoute
  CoursesIdRoute: typeof CoursesIdRoute
  LivreursIdRoute: typeof LivreursIdRoute
  PartenairesIdRoute: typeof PartenairesIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LivreursIndexRoute: typeof LivreursIndexRoute
  PartenairesIndexRoute: typeof PartenairesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerciaux': {
      id: '/commerciaux'
      path: '/commerciaux'
      fullPath: '/commerciaux'
      preLoaderRoute: typeof CommerciauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarification': {
      id: '/tarification'
      path: '/tarification'
      fullPath: '/tarification'
      preLoaderRoute: typeof TarificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreurs/': {
      id: '/livreurs/'
      path: '/livreurs'
      fullPath: '/livreurs/'
      preLoaderRoute: typeof LivreursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreurs/$id': {
      id: '/livreurs/$id'
      path: '/livreurs/$id'
      fullPath: '/livreurs/$id'
      preLoaderRoute: typeof LivreursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires/': {
      id: '/partenaires/'
      path: '/partenaires'
      fullPath: '/partenaires/'
      preLoaderRoute: typeof PartenairesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires/$id': {
      id: '/partenaires/$id'
      path: '/partenaires/$id'
      fullPath: '/partenaires/$id'
      preLoaderRoute: typeof PartenairesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencesRoute: AgencesRoute,
  CommerciauxRoute: CommerciauxRoute,
  DispatchRoute: DispatchRoute,
  PaiementsRoute: PaiementsRoute,
  TarificationRoute: TarificationRoute,
  CoursesIdRoute: CoursesIdRoute,
  LivreursIdRoute: LivreursIdRoute,
  PartenairesIdRoute: PartenairesIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LivreursIndexRoute: LivreursIndexRoute,
  PartenairesIndexRoute: PartenairesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
