/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgencesRouteImport } from './routes/agences'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as LivreursIndexRouteImport } from './routes/livreurs.index'
import { Route as LivreursIdRouteImport } from './routes/livreurs.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgencesRoute = AgencesRouteImport.update({
  id: '/agences',
  path: '/agences',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreursIndexRoute = LivreursIndexRouteImport.update({
  id: '/livreurs/',
  path: '/livreurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LivreursIdRoute = LivreursIdRouteImport.update({
  id: '/livreurs/$id',
  path: '/livreurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/dispatch': typeof DispatchRoute
  '/courses/$id': typeof CoursesIdRoute
  '/livreurs/$id': typeof LivreursIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/livreurs/': typeof LivreursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/dispatch': typeof DispatchRoute
  '/courses/$id': typeof CoursesIdRoute
  '/livreurs/$id': typeof LivreursIdRoute
  '/courses': typeof CoursesIndexRoute
  '/livreurs': typeof LivreursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agences': typeof AgencesRoute
  '/dispatch': typeof DispatchRoute
  '/courses/$id': typeof CoursesIdRoute
  '/livreurs/$id': typeof LivreursIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/livreurs/': typeof LivreursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agences'
    | '/dispatch'
    | '/courses/$id'
    | '/livreurs/$id'
    | '/courses/'
    | '/livreurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agences'
    | '/dispatch'
    | '/courses/$id'
    | '/livreurs/$id'
    | '/courses'
    | '/livreurs'
  id:
    | '__root__'
    | '/'
    | '/agences'
    | '/dispatch'
    | '/courses/$id'
    | '/livreurs/$id'
    | '/courses/'
    | '/livreurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgencesRoute: typeof AgencesRoute
  DispatchRoute: typeof DispatchRoute
  CoursesIdRoute: typeof CoursesIdRoute
  LivreursIdRoute: typeof LivreursIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LivreursIndexRoute: typeof LivreursIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agences': {
      id: '/agences'
      path: '/agences'
      fullPath: '/agences'
      preLoaderRoute: typeof AgencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreurs/': {
      id: '/livreurs/'
      path: '/livreurs'
      fullPath: '/livreurs/'
      preLoaderRoute: typeof LivreursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livreurs/$id': {
      id: '/livreurs/$id'
      path: '/livreurs/$id'
      fullPath: '/livreurs/$id'
      preLoaderRoute: typeof LivreursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgencesRoute: AgencesRoute,
  DispatchRoute: DispatchRoute,
  CoursesIdRoute: CoursesIdRoute,
  LivreursIdRoute: LivreursIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LivreursIndexRoute: LivreursIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
